language: java
jdk:
  - oraclejdk11
addons:
  sonarcloud:
    organization: "sergant1987"
    token:
      secure: "2ff04e4f8be0771f68e73c18be08b8ca965e3bd1" # encrypted value of your

services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE medcards;" -U postgres
  -
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Sergant1987_levelup-jj
