language: java
jdk:
  - oraclejdk11
addons:
  sonarcloud:
    organization: "sergant1987"
    token:
      secure: "552cf00f9a487995223d3bfacf058a02fb948176" # encrypted value of your

#before_script:
#  - psql -c "CREATE DATABASE medcards;" -U postgres
#  - psql -c "CREATE USER postgres WITH PASSWORD 'root';" -U postgres

#script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
#  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Sergant1987_levelup-jj
