language: java
jdk:
  - oraclejdk11
addons:
  sonarcloud:
    organization: "sergant1987"
    token:
      secure: "fa09445e09d45a6b48c4cb03b4d529cf845fef32" # encrypted value of your token

services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE medcards;" -U postgres

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Sergant1987_levelup-jj
